package com.shms.controller;
import com.shms.dto.AppointmentView;import com.shms.entity.*;import com.shms.repository.*;import com.shms.service.*;import jakarta.servlet.http.HttpSession;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.web.bind.annotation.*;import java.time.*;import java.util.List;
@Controller @RequestMapping("/appointments") public class AppointmentController{
 private final AppointmentRepository repo;private final DoctorRepository doctors;private final PatientRepository patients;private final AppointmentService service;private final ActivityService activities;private final NotificationService notifications;
 public AppointmentController(AppointmentRepository r,DoctorRepository d,PatientRepository p,AppointmentService s,ActivityService a,NotificationService n){repo=r;doctors=d;patients=p;service=s;activities=a;notifications=n;}
 @GetMapping("/book") public String booking(@RequestParam Long doctorId,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate date,HttpSession s,Model m){
  User u=current(s); if(u==null) return "redirect:/login"; if(!"PATIENT".equals(u.getRole())) return "redirect:"+dashboardFor(u.getRole());Doctor d=doctors.findById(doctorId).orElseThrow();LocalDate day=date==null?LocalDate.now().plusDays(1):date;m.addAttribute("doctor",d);m.addAttribute("selectedDate",day);m.addAttribute("slots",service.availableSlots(d,day));return "listAppointments";}
 @PostMapping("/bookSlot") public String book(@RequestParam Long doctorId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate date,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.TIME)LocalTime startTime,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.TIME)LocalTime endTime,@RequestParam(required=false)String reason,HttpSession s,Model m){User u=current(s);if(u==null)return "redirect:/login";Patient p=patients.findByUserId(u.getId()).orElseThrow();Doctor d=doctors.findById(doctorId).orElseThrow();if(service.availableSlots(d,date).stream().noneMatch(x->x.startTime().equals(startTime)&&x.endTime().equals(endTime))){m.addAttribute("error","That appointment slot is no longer available.");return booking(doctorId,date,s,m);}try { var a=service.createBooking(d,p,date,startTime,endTime,reason); activities.publish("Appointment "+a.getAppointmentNumber()+" booked by "+p.getFullName(),u.getEmail(),"APPOINTMENT"); notifications.send(d.getUser(),"New appointment booked","A patient has booked "+a.getAppointmentNumber()+" for "+a.getDate()+" at "+a.getStartTime()+".",Notification.Type.APPOINTMENT); notifications.send(u,"Appointment confirmed","Your appointment "+a.getAppointmentNumber()+" with "+d.getFullName()+" is confirmed.",Notification.Type.APPOINTMENT); return "redirect:/appointments/my"; } catch (RuntimeException ex) { m.addAttribute("error", ex.getMessage()==null?"The appointment could not be booked.":ex.getMessage()); return booking(doctorId,date,s,m); }}
 @GetMapping("/my") public String my(HttpSession s,Model m){User u=current(s);if(u==null)return "redirect:/login";Patient p=patients.findByUserId(u.getId()).orElseThrow();m.addAttribute("appointments",repo.findByPatientId(p.getId()));return "my_appointments";}
 @PostMapping("/cancel/{id}") public String cancel(@PathVariable Long id,HttpSession s){User u=current(s);if(u==null)return "redirect:/login";Patient p=patients.findByUserId(u.getId()).orElseThrow();repo.findById(id).filter(a->a.getPatient()!=null&&a.getPatient().getId().equals(p.getId())).ifPresent(a->{a.setStatus(Appointment.AppointmentStatus.CANCELLED);repo.save(a);});return "redirect:/appointments/my";}
 private User current(HttpSession s){Object o=s.getAttribute("currentUser");return o instanceof User?(User)o:null;}
 private String dashboardFor(String role){return switch(role){case "ADMIN"->"/admin-dashboard";case "DOCTOR"->"/doctors/dashboard";case "RECEPTIONIST"->"/reception-dashboard";case "NURSE","PHARMACIST","LAB_TECHNICIAN"->"/staff-dashboard";default->"/patient-dashboard";};}
}
