package com.shms.controller;
import com.shms.dto.AppointmentSlotView;import com.shms.entity.*;import com.shms.repository.*;import com.shms.service.*;import jakarta.servlet.http.HttpSession;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.web.bind.annotation.*;import java.time.*;import java.util.List;
@Controller @RequestMapping("/appointments") public class AppointmentController{
 private final AppointmentSlotRepository repo;private final DoctorRepository doctors;private final PatientRepository patients;private final AppointmentService service;private final ActivityService activities;
 public AppointmentController(AppointmentSlotRepository r,DoctorRepository d,PatientRepository p,AppointmentService s,ActivityService a){repo=r;doctors=d;patients=p;service=s;activities=a;}
 @GetMapping("/book") public String booking(@RequestParam Long doctorId,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate date,Model m){Doctor d=doctors.findById(doctorId).orElseThrow();LocalDate day=date==null?LocalDate.now().plusDays(1):date;m.addAttribute("doctor",d);m.addAttribute("selectedDate",day);m.addAttribute("slots",service.availableSlots(d,day));return "listAppointments";}
 @PostMapping("/bookSlot") public String book(@RequestParam Long doctorId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate date,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.TIME)LocalTime startTime,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.TIME)LocalTime endTime,@RequestParam(required=false)String reason,HttpSession s,Model m){User u=current(s);if(u==null)return "redirect:/login";Patient p=patients.findByUserId(u.getId()).orElseThrow();Doctor d=doctors.findById(doctorId).orElseThrow();if(service.availableSlots(d,date).stream().noneMatch(x->x.startTime().equals(startTime)&&x.endTime().equals(endTime))){m.addAttribute("error","That appointment slot is no longer available.");return booking(doctorId,date,m);}var a=service.createBooking(d,p,date,startTime,endTime,reason);activities.publish("Appointment "+a.getAppointmentNumber()+" booked by "+p.getFullName(),u.getEmail(),"APPOINTMENT");return "redirect:/appointments/my";}
 @GetMapping("/my") public String my(HttpSession s,Model m){User u=current(s);if(u==null)return "redirect:/login";Patient p=patients.findByUserId(u.getId()).orElseThrow();m.addAttribute("appointments",repo.findByPatientId(p.getId()));return "my_appointments";}
 @PostMapping("/cancel/{id}") public String cancel(@PathVariable Long id,HttpSession s){User u=current(s);if(u==null)return "redirect:/login";Patient p=patients.findByUserId(u.getId()).orElseThrow();repo.findById(id).filter(a->a.getPatient()!=null&&a.getPatient().getId().equals(p.getId())).ifPresent(a->{a.setPatient(null);a.setStatus(AppointmentSlot.AppointmentStatus.CANCELLED);repo.save(a);});return "redirect:/appointments/my";}
 private User current(HttpSession s){Object o=s.getAttribute("currentUser");return o instanceof User?(User)o:null;}
}
